2024-02-10 13:45:58,700 INFO Watching for file changes with StatReloader
2024-02-10 13:46:43,640 INFO Watching for file changes with StatReloader
2024-02-10 13:48:13,216 INFO /usr/src/app/dcelery/celery_tasks/ex1_try_except.py changed, reloading.
2024-02-10 13:48:14,193 INFO Watching for file changes with StatReloader
2024-02-10 13:48:15,397 INFO /usr/src/app/dcelery/celery_tasks/ex1_try_except.py changed, reloading.
2024-02-10 13:48:16,392 INFO Watching for file changes with StatReloader
2024-02-10 13:48:19,630 INFO /usr/src/app/dcelery/celery_tasks/ex1_try_except.py changed, reloading.
2024-02-10 13:48:20,613 INFO Watching for file changes with StatReloader
2024-02-10 13:48:27,921 INFO /usr/src/app/dcelery/celery_tasks/ex1_try_except.py changed, reloading.
2024-02-10 13:48:28,907 INFO Watching for file changes with StatReloader
2024-02-10 13:48:31,130 INFO /usr/src/app/dcelery/celery_tasks/ex1_try_except.py changed, reloading.
2024-02-10 13:48:32,113 INFO Watching for file changes with StatReloader
2024-02-10 13:48:41,446 INFO /usr/src/app/dcelery/celery_tasks/ex1_try_except.py changed, reloading.
2024-02-10 13:48:42,435 INFO Watching for file changes with StatReloader
2024-02-10 13:48:44,661 INFO /usr/src/app/dcelery/celery_tasks/ex1_try_except.py changed, reloading.
2024-02-10 13:48:45,646 INFO Watching for file changes with StatReloader
2024-02-10 13:48:51,933 INFO /usr/src/app/dcelery/celery_tasks/ex1_try_except.py changed, reloading.
2024-02-10 13:48:52,929 INFO Watching for file changes with StatReloader
2024-02-10 14:02:51,508 INFO /usr/src/app/dcelery/celery_tasks/ex1_try_except.py changed, reloading.
2024-02-10 14:02:52,499 INFO Watching for file changes with StatReloader
2024-02-10 14:03:02,855 INFO /usr/src/app/dcelery/celery_tasks/ex1_try_except.py changed, reloading.
2024-02-10 14:03:03,857 INFO Watching for file changes with StatReloader
2024-02-10 14:08:08,888 INFO /usr/src/app/dcelery/celery_tasks/ex1_try_except.py changed, reloading.
2024-02-10 14:29:47,012 INFO Watching for file changes with StatReloader
2024-02-10 15:21:03,129 INFO /usr/src/app/dcelery/celery_config.py changed, reloading.
2024-02-10 15:21:04,147 INFO Watching for file changes with StatReloader
2024-02-10 15:21:06,420 INFO /usr/src/app/dcelery/celery_config.py changed, reloading.
2024-02-10 15:21:07,485 INFO Watching for file changes with StatReloader
2024-02-10 15:21:11,795 INFO /usr/src/app/dcelery/celery_config.py changed, reloading.
2024-02-10 15:21:46,121 INFO Watching for file changes with StatReloader
2024-02-10 15:25:19,781 INFO Watching for file changes with StatReloader
2024-02-10 15:27:06,515 INFO Watching for file changes with StatReloader
2024-02-10 15:35:47,219 INFO Watching for file changes with StatReloader
2024-02-10 16:54:56,726 INFO Watching for file changes with StatReloader
2024-02-10 16:58:56,825 INFO Watching for file changes with StatReloader
2024-02-10 17:07:50,337 INFO Watching for file changes with StatReloader
2024-02-10 17:11:29,855 INFO /usr/src/app/dcelery/celery_tasks/ex11_task_scheduling.py changed, reloading.
2024-02-10 17:11:30,917 INFO Watching for file changes with StatReloader
2024-02-10 17:11:32,187 INFO /usr/src/app/dcelery/celery_tasks/ex11_task_scheduling.py changed, reloading.
2024-02-10 17:11:33,262 INFO Watching for file changes with StatReloader
2024-02-10 17:11:34,546 INFO /usr/src/app/dcelery/celery_tasks/ex11_task_scheduling.py changed, reloading.
2024-02-10 17:11:35,690 INFO Watching for file changes with StatReloader
2024-02-10 19:51:36,469 INFO /usr/src/app/dcelery/settings.py changed, reloading.
2024-02-10 19:51:37,532 INFO Watching for file changes with StatReloader
2024-02-10 19:51:41,810 INFO /usr/src/app/dcelery/settings.py changed, reloading.
2024-02-10 19:51:42,893 INFO Watching for file changes with StatReloader
2024-02-10 19:51:44,121 INFO /usr/src/app/dcelery/settings.py changed, reloading.
2024-02-10 19:51:45,197 INFO Watching for file changes with StatReloader
2024-02-10 19:51:46,426 INFO /usr/src/app/dcelery/settings.py changed, reloading.
2024-02-10 19:51:47,511 INFO Watching for file changes with StatReloader
2024-02-10 19:51:49,768 INFO /usr/src/app/dcelery/settings.py changed, reloading.
2024-02-10 19:51:50,867 INFO Watching for file changes with StatReloader
2024-02-10 19:52:44,391 ERROR Signal handler <bound method DjangoFixup.on_import_modules of <celery.fixups.django.DjangoFixup object at 0x7f40f7d2aa80>> raised: ModuleNotFoundError("No module named 'django_celery_beat'")
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/celery/utils/dispatch/signal.py", line 276, in send
    response = receiver(signal=self, sender=sender, **named)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/celery/fixups/django.py", line 97, in on_import_modules
    self.worker_fixup.validate_models()
  File "/usr/local/lib/python3.12/site-packages/celery/fixups/django.py", line 135, in validate_models
    self.django_setup()
  File "/usr/local/lib/python3.12/site-packages/celery/fixups/django.py", line 131, in django_setup
    django.setup()
  File "/usr/local/lib/python3.12/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.12/site-packages/django/apps/registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
                 ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/apps/config.py", line 193, in create
    import_module(entry)
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1324, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'django_celery_beat'
2024-02-10 19:52:44,393 ERROR Signal handler <promise@0x7f40f7d51b30 --> <bound method Celery._autodiscover_tasks of <Celery dcelery at 0x7f40f7d46ab0>>> raised: AppRegistryNotReady("Apps aren't loaded yet.")
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/celery/utils/dispatch/signal.py", line 276, in send
    response = receiver(signal=self, sender=sender, **named)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/vine/promises.py", line 161, in __call__
    return self.throw()
           ^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/vine/promises.py", line 158, in __call__
    retval = fun(*final_args, **final_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/celery/app/base.py", line 692, in _autodiscover_tasks
    return self._autodiscover_tasks_from_fixups(related_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/celery/app/base.py", line 704, in _autodiscover_tasks_from_fixups
    for pkg in fixup.autodiscover_tasks()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/celery/fixups/django.py", line 107, in autodiscover_tasks
    return [config.name for config in apps.get_app_configs()]
                                      ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/apps/registry.py", line 147, in get_app_configs
    self.check_apps_ready()
  File "/usr/local/lib/python3.12/site-packages/django/apps/registry.py", line 138, in check_apps_ready
    raise AppRegistryNotReady("Apps aren't loaded yet.")
django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet.
2024-02-10 19:52:54,106 INFO Watching for file changes with StatReloader
2024-02-10 19:53:02,532 INFO Watching for file changes with StatReloader
2024-02-10 21:13:10,360 ERROR Signal handler <bound method DjangoFixup.on_import_modules of <celery.fixups.django.DjangoFixup object at 0x7f8c841f5880>> raised: ModuleNotFoundError("No module named 'django_celery_beat'")
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/celery/utils/dispatch/signal.py", line 276, in send
    response = receiver(signal=self, sender=sender, **named)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/celery/fixups/django.py", line 97, in on_import_modules
    self.worker_fixup.validate_models()
  File "/usr/local/lib/python3.12/site-packages/celery/fixups/django.py", line 135, in validate_models
    self.django_setup()
  File "/usr/local/lib/python3.12/site-packages/celery/fixups/django.py", line 131, in django_setup
    django.setup()
  File "/usr/local/lib/python3.12/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.12/site-packages/django/apps/registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
                 ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/apps/config.py", line 193, in create
    import_module(entry)
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1324, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'django_celery_beat'
2024-02-10 21:13:10,363 ERROR Signal handler <promise@0x7f8c84205b30 --> <bound method Celery._autodiscover_tasks of <Celery dcelery at 0x7f8c841f6ea0>>> raised: AppRegistryNotReady("Apps aren't loaded yet.")
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/celery/utils/dispatch/signal.py", line 276, in send
    response = receiver(signal=self, sender=sender, **named)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/vine/promises.py", line 161, in __call__
    return self.throw()
           ^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/vine/promises.py", line 158, in __call__
    retval = fun(*final_args, **final_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/celery/app/base.py", line 692, in _autodiscover_tasks
    return self._autodiscover_tasks_from_fixups(related_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/celery/app/base.py", line 704, in _autodiscover_tasks_from_fixups
    for pkg in fixup.autodiscover_tasks()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/celery/fixups/django.py", line 107, in autodiscover_tasks
    return [config.name for config in apps.get_app_configs()]
                                      ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/apps/registry.py", line 147, in get_app_configs
    self.check_apps_ready()
  File "/usr/local/lib/python3.12/site-packages/django/apps/registry.py", line 138, in check_apps_ready
    raise AppRegistryNotReady("Apps aren't loaded yet.")
django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet.
2024-02-10 21:13:11,309 INFO Watching for file changes with StatReloader
2024-02-10 21:13:36,987 INFO /usr/src/app/dcelery/settings.py changed, reloading.
2024-02-10 21:13:38,058 INFO Watching for file changes with StatReloader
2024-02-10 21:14:38,004 INFO Watching for file changes with StatReloader
